### ISSUE TITLE
Test failures with 3.12.0b0+

### ISSUE THREAD

**Issue by mweinelt** [Bluetooth-Devices/aiohttp-fast-zlib#53]
**Describe the bug**
https://github.com/aio-libs/aiohttp/commit/5268479e62179542539d968222081bef1569956c#diff-ee4684490fc008050aca8aa9ade6b09dc011354d6663526e0b2f3602aecd5563 removes the zlib import from `aiohttp._websocket.writer`, which breaks two tests trying to access that attribute:

-  test_enable_disable_greater_than_311
- test_enable_disable_when_all_missing_greater_than_311

**To Reproduce**
Update to aiohttp 3.12.0b0 or later and run the test suite.

**Additional context**
```pytb
_____________________ test_enable_disable_greater_than_311 _____________________

    @pytest.mark.skipif(
        aiohttp_fast_zlib._AIOHTTP_VERSION < (3, 11),
        reason="Only works with aiohttp >= 3.11",
    )
    def test_enable_disable_greater_than_311():
        """Test enable/disable."""
        from aiohttp._websocket import writer
    
>       assert writer.zlib is zlib_original
E       AttributeError: module 'aiohttp._websocket.writer' has no attribute 'zlib'

tests/test_init.py:42: AttributeError
____________ test_enable_disable_when_all_missing_greater_than_311 _____________

    @pytest.mark.skipif(
        aiohttp_fast_zlib._AIOHTTP_VERSION < (3, 11),
        reason="Only works with aiohttp >= 3.11",
    )
    def test_enable_disable_when_all_missing_greater_than_311():
        """Test enable/disable."""
        from aiohttp._websocket import writer
    
        with patch.object(aiohttp_fast_zlib, "best_zlib", zlib_original):
>           assert writer.zlib is zlib_original
E           AttributeError: module 'aiohttp._websocket.writer' has no attribute 'zlib'

tests/test_init.py:61: AttributeError

**Comment by mweinelt** [comment]
This section probably needs an update as well.

https://github.com/Bluetooth-Devices/aiohttp-fast-zlib/blob/104007ada635d31a0d0751ab4560bf9fe9216cfb/src/aiohttp_fast_zlib/__init__.py#L61-L64
